language: go
sudo: required
services:
- docker

dist: xenial

# This moves Kubernetes specific config files.
env:
- CHANGE_MINIKUBE_NONE_USER=true

notifications:
  email:
    on_success: never
    on_failure: change

jobs:
  include:
    - stage: build
      script: bash -f ./scripts/installtools.sh && make
    - stage: integration-test
      script: bash -f ./scripts/startminikube_travis.sh && make integration